# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ciberseguridad_2026',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/ciberseguridad_2026',
                'lib_path': 'ciberseguridad_2026'},
  'syms': {'ciberseguridad_2026.core': {'ciberseguridad_2026.core.foo': ('core.html#foo', 'ciberseguridad_2026/core.py')}}}
